from machine import ADC
from machine import Pin, Timer
from time import sleep
import math
adc = ADC(26)
g=Pin(16,Pin.OUT)
f=Pin(17,Pin.OUT)
a=Pin(18,Pin.OUT)
b=Pin(19,Pin.OUT)
c=Pin(13,Pin.OUT)
d=Pin(14,Pin.OUT)
e=Pin(15,Pin.OUT)
d1=Pin(12,Pin.OUT)
d2=Pin(11,Pin.OUT)
d3=Pin(10,Pin.OUT)
d4=Pin(9,Pin.OUT)
analog=0
def birler(analog):
    birler=math.floor(analog%10)
    if birler == 0:
     g.value(0)
     f.value(1)
     a.value(1)
     b.value(1)
     c.value(1)
     d.value(1)
     e.value(1)
     d4.value(1)
    if birler == 1:
     g.value(0)
     f.value(0)
     a.value(0)
     b.value(1)
     c.value(1)
     d.value(0)
     e.value(0)
     d4.value(1)
    if birler == 2:
     g.value(1)
     f.value(0)
     a.value(1)
     b.value(1)
     c.value(0)
     d.value(1)
     e.value(1)
     d4.value(1)
    if birler == 3:
     g.value(1)
     f.value(0)
     a.value(1)
     b.value(1)
     c.value(1)
     d.value(1)
     e.value(0)
     d4.value(1)
    if birler == 4:
     g.value(1)
     f.value(1)
     a.value(0)
     b.value(1)
     c.value(1)
     d.value(0)
     e.value(0)
     d4.value(1)
    if birler == 5:
     g.value(1)
     f.value(1)
     a.value(1)
     b.value(0)
     c.value(1)
     d.value(1)
     e.value(0)
     d4.value(1)
    if birler == 6:
     g.value(1)
     f.value(1)
     a.value(1)
     b.value(0)
     c.value(1)
     d.value(1)
     e.value(1)
     d4.value(1)
    if birler == 7:
     g.value(0)
     f.value(0)
     a.value(1)
     b.value(1)
     c.value(1)
     d.value(0)
     e.value(0)
     d4.value(1)
    if birler == 8:
     g.value(1)
     f.value(1)
     a.value(1)
     b.value(1)
     c.value(1)
     d.value(1)
     e.value(1)
     d4.value(1)
    if birler == 9:
     g.value(1)
     f.value(1)
     a.value(1)
     b.value(1)
     c.value(1)
     d.value(1)
     e.value(0)
     d4.value(1)
    d4.value(0)
def onlar(analog):
    onlar=math.floor(analog/10)%10    
    if onlar == 0:
     g.value(0)
     f.value(1)
     a.value(1)
     b.value(1)
     c.value(1)
     d.value(1)
     e.value(1)
     d3.value(1)
    if onlar == 1:
     g.value(0)
     f.value(0)
     a.value(0)
     b.value(1)
     c.value(1)
     d.value(0)
     e.value(0)
     d3.value(1)
    if onlar == 2:
     g.value(1)
     f.value(0)
     a.value(1)
     b.value(1)
     c.value(0)
     d.value(1)
     e.value(1)
     d3.value(1)
    if onlar == 3:
     g.value(1)
     f.value(0)
     a.value(1)
     b.value(1)
     c.value(1)
     d.value(1)
     e.value(0)
     d3.value(1)
    if onlar == 4:
     g.value(1)
     f.value(1)
     a.value(0)
     b.value(1)
     c.value(1)
     d.value(0)
     e.value(0)
     d3.value(1)
    if onlar == 5:
     g.value(1)
     f.value(1)
     a.value(1)
     b.value(0)
     c.value(1)
     d.value(1)
     e.value(0)
     d3.value(1)
    if onlar == 6:
     g.value(1)
     f.value(1)
     a.value(1)
     b.value(0)
     c.value(1)
     d.value(1)
     e.value(1)
     d3.value(1)
    if onlar == 7:
     g.value(0)
     f.value(0)
     a.value(1)
     b.value(1)
     c.value(1)
     d.value(0)
     e.value(0)
     d3.value(1)
    if onlar == 8:
     g.value(1)
     f.value(1)
     a.value(1)
     b.value(1)
     c.value(1)
     d.value(1)
     e.value(1)
     d3.value(1)
    if onlar == 9:
     g.value(1)
     f.value(1)
     a.value(1)
     b.value(1)
     c.value(1)
     d.value(1)
     e.value(0)
     d3.value(1)
    d3.value(0)
def yuzler(analog):
    yuzler=math.floor(analog/100)%10
    if yuzler == 0:
     g.value(0)
     f.value(1)
     a.value(1)
     b.value(1)
     c.value(1)
     d.value(1)
     e.value(1)
     d2.value(1)
    if yuzler == 1:
     g.value(0)
     f.value(0)
     a.value(0)
     b.value(1)
     c.value(1)
     d.value(0)
     e.value(0)
     d2.value(1)
    if yuzler == 2:
     g.value(1)
     f.value(0)
     a.value(1)
     b.value(1)
     c.value(0)
     d.value(1)
     e.value(1)
     d2.value(1)
    if yuzler == 3:
     g.value(1)
     f.value(0)
     a.value(1)
     b.value(1)
     c.value(1)
     d.value(1)
     e.value(0)
     d2.value(1)
    if yuzler == 4:
     g.value(1)
     f.value(1)
     a.value(0)
     b.value(1)
     c.value(1)
     d.value(0)
     e.value(0)
     d2.value(1)
    if yuzler == 5:
     g.value(1)
     f.value(1)
     a.value(1)
     b.value(0)
     c.value(1)
     d.value(1)
     e.value(0)
     d2.value(1)
    if yuzler == 6:
     g.value(1)
     f.value(1)
     a.value(1)
     b.value(0)
     c.value(1)
     d.value(1)
     e.value(1)
     d2.value(1)
    if yuzler == 7:
     g.value(0)
     f.value(0)
     a.value(1)
     b.value(1)
     c.value(1)
     d.value(0)
     e.value(0)
     d2.value(1)
    if yuzler == 8:
     g.value(1)
     f.value(1)
     a.value(1)
     b.value(1)
     c.value(1)
     d.value(1)
     e.value(1)
     d2.value(1)
    if yuzler == 9:
     g.value(1)
     f.value(1)
     a.value(1)
     b.value(1)
     c.value(1)
     d.value(1)
     e.value(0)
     d2.value(1)
    d2.value(0)
def binler(analog):
    binler=math.floor(analog/1000)
    if binler == 0:
     g.value(0)
     f.value(1)
     a.value(1)
     b.value(1)
     c.value(1)
     d.value(1)
     e.value(1)
     d1.value(1)
     d1.value(1)
    if binler == 1:
     g.value(0)
     f.value(0)
     a.value(0)
     b.value(1)
     c.value(1)
     d.value(0)
     e.value(0)
     d1.value(1)
    if binler == 2:
     g.value(1)
     f.value(0)
     a.value(1)
     b.value(1)
     c.value(0)
     d.value(1)
     e.value(1)
     d1.value(1)
    if binler == 3:
     g.value(1)
     f.value(0)
     a.value(1)
     b.value(1)
     c.value(1)
     d.value(1)
     e.value(0)
     d1.value(1)
    if binler == 4:
     g.value(1)
     f.value(1)
     a.value(0)
     b.value(1)
     c.value(1)
     d.value(0)
     e.value(0)
     d1.value(1)
    if binler == 5:
     g.value(1)
     f.value(1)
     a.value(1)
     b.value(0)
     c.value(1)
     d.value(1)
     e.value(0)
     d1.value(1)
    if binler == 6:
     g.value(1)
     f.value(1)
     a.value(1)
     b.value(0)
     c.value(1)
     d.value(1)
     e.value(1)
     d1.value(1)
    if binler == 7:
     g.value(0)
     f.value(0)
     a.value(1)
     b.value(1)
     c.value(1)
     d.value(0)
     e.value(0)
     d1.value(1)
    if binler == 8:
     g.value(1)
     f.value(1)
     a.value(1)
     b.value(1)
     c.value(1)
     d.value(1)
     e.value(1)
     d1.value(1)
    if binler == 9:
     g.value(1)
     f.value(1)
     a.value(1)
     b.value(1)
     c.value(1)
     d.value(1)
     e.value(0)
     d1.value(1)
    d1.value(0)
tim = Timer()
def tick(timer):
    global analog
    analog = round(adc.read_u16()/16)
tim.init(freq=3, mode=Timer.PERIODIC, callback=tick)
while True:
    #print("analog deger: ")
    #print(analog)
    binler(analog)
    yuzler(analog)
    onlar(analog)
    birler(analog)

